layout_spectrum: 0.1876282
color:
  saturation: 0.4735368
  lightness: 0.3589663
  brandStrength: 0.442789
  rhythmicContrast: 0.9915923
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 1
name: Narfd
